### ISSUE TITLE
Introduce a mode where animations are all instant

### ISSUE THREAD

**Issue by coyotte508** [po-devs/po-battle-window#6]
And maybe a way to adjust all animation length by a float.

It would be triggered by the battle:

`this.trigger("animation-duration-multiplier", 0.f)`, `this.trigger("animation-duration-multiplier", 0.5f)`, `this.trigger("animation-duration-multiplier", 1.f)`, `this.trigger("animation-duration-multiplier", 2.f)`.

Allows to do next turn easily in replays, and different speeds in replays. Useful for bug reports as well.

**Comment by MidwayMarshall** [comment]
I think a temporal shift might do this nicely

delta = ().getDeltaTime \* 0.5
means time will appear to flow at half speed
